name: deploy-to-aliyun

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

    steps:
      - uses: actions/checkout@v1
      - name: login to Aliyun
        env:
          NAME: ${{secrets.ALI_REGISTRY_USERNAME}}
          PASS: ${{secrets.ALI_REGISTRY_PASSWORD}}
        run: docker login -u francissmajere@qq.com -p $PASS registry.cn-hongkong.aliyuncs.com
      - run: docker build -t registry.cn-hongkong.aliyuncs.com/infiniteprimes/jiu-pan:0.0.1 .
      - run: docker push registry.cn-hongkong.aliyuncs.com/infiniteprimes/jiu-pan:0.0.1
      - run: curl https://cs.console.aliyun.com/hook/trigger?token=eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJjbHVzdGVySWQiOiJjOTMwZmQyMDAyMDE3NDMxODk2MTRiMGQ2YzJkZWY2N2QiLCJpZCI6IjIyNjkwMyJ9.pNtb3ERCjbBV0Vgo-3-lzyBzi6-5DniayzXLW0CRp-fLhtAv6ktZt-jWQCH6TNfJe_gemOQfDYvWD0Zp2D_5D7PuFwQQwnAfRA8OIW8HlphhItkcluJFm3_3hIFLbeW5ou4Dbnrvm05NCeB68LW6WR8uh7bFhvplj-6r4RPGGvY

      # - uses: act10ns/slack@v1
      #   with:
      #     status: ${{job.status}}
      #     channel: '#fengheli'
      #   if: always()